"""empty message

Revision ID: 503753660a2d
Revises: 4ad04cfe09fc
Create Date: 2023-12-03 19:52:07.576350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503753660a2d'
down_revision = '4ad04cfe09fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
