"""empty message

Revision ID: a3e6a318ebac
Revises: 503753660a2d
Create Date: 2024-01-16 16:00:53.217363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e6a318ebac'
down_revision = '503753660a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pflanze', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('whatever', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    
    dummy = 1
    # ### commands auto generated by Alembic - please adjust! ###

    #kommentiere ich aktuell nur aus, da fehlerhaft, aber nicht benötigt
    #with op.batch_alter_table('pflanze', schema=None) as batch_op:
    #    batch_op.drop_constraint(None, type_='foreignkey')
    #    batch_op.drop_column('created_by')

    # ### end Alembic commands ###
